import React from "react";

const PrintTemplate = ({ 
  title, 
  children, 
  isTable = true,
  clientName,
  toiletId,
  location,
  clientLogo
}) => {
  const currentDate = new Date();
  const dateStr = currentDate.toLocaleDateString();
  const timeStr = currentDate.toLocaleTimeString();
  const reportId = `RPT-${Math.floor(Math.random() * 100000000)}`;

  const Header = () => (
    <div className="print-header-content" style={{ display: 'flex', flexDirection: 'column', width: '100%', marginBottom: '20px', fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px', width: '100%' }}>
        {/* Left Side: Client Logo */}
        <div style={{ width: '160px', display: 'flex', alignItems: 'center', justifyContent: 'flex-start' }}>
          <img src={clientLogo || "/logo_left.jpeg"} alt="Client Logo" style={{ maxHeight: '65px', maxWidth: '150px', objectFit: 'contain' }} />
        </div>

        {/* Center: Title & Details exactly matching HD PDF */}
        <div style={{ textAlign: 'center', flexGrow: 1, padding: '0 15px' }}>
          <h2 style={{ margin: '0 0 6px 0', color: '#059669', fontSize: '17pt', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            {title}
          </h2>
          {clientName && (
            <div style={{ color: '#1d4ed8', fontSize: '11pt', fontWeight: '700', marginBottom: '6px' }}>
              Client Name: {clientName}
            </div>
          )}
          {(toiletId || location) && (
            <div style={{ color: 'var(--slate-700)', fontSize: '10pt', fontWeight: '600', marginBottom: '6px' }}>
              {toiletId && <span>Toilet ID: <strong style={{ color: 'var(--slate-900)' }}>{toiletId}</strong></span>}
              {toiletId && location && <span style={{ margin: '0 10px', color: 'var(--slate-300)' }}>|</span>}
              {location && <span>Location: <strong style={{ color: 'var(--slate-900)' }}>{location}</strong></span>}
            </div>
          )}
          <div style={{ fontSize: '8.5pt', color: 'var(--slate-500)', marginTop: '4px', fontWeight: '500' }}>
            Report ID: <span style={{ fontFamily: 'monospace' }}>{reportId}</span> &nbsp;|&nbsp; Generated Date: {dateStr}, {timeStr}
          </div>
        </div>

        {/* Right Side: SmartBuddy Modern HD Logo */}
        <div style={{ width: '160px', display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
          <img src="/logo_new.png" alt="SmartBuddy Logo" style={{ maxHeight: '65px', maxWidth: '150px', objectFit: 'contain' }} />
        </div>
      </div>
      <div style={{ borderBottom: '2.5px solid #1d4ed8' }}></div>
    </div>
  );

  const Footer = () => (
    <div className="print-footer-content" style={{ width: '100%', marginTop: '40px', fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '25px', padding: '0 20px' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '160px', borderTop: '1.5px solid #475569', marginBottom: '6px' }}></div>
          <span style={{ fontSize: '10pt', fontWeight: '700', color: 'var(--slate-700)' }}>System Administrator</span>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ width: '160px', borderTop: '1.5px solid #475569', marginBottom: '6px' }}></div>
          <span style={{ fontSize: '10pt', fontWeight: '700', color: 'var(--slate-700)' }}>Authorized Signatory</span>
        </div>
      </div>
      <div style={{ borderTop: '1.5px solid #cbd5e1', paddingTop: '10px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', fontSize: '8.5pt', color: 'var(--slate-600)', lineHeight: '1.5' }}>
        <div style={{ textAlign: 'left', flex: 1, paddingRight: '15px' }}>
          <div style={{ fontWeight: '700', color: 'var(--slate-800)' }}>AARYA INNOVTECH PVT. LTD. &nbsp;|&nbsp; CIN: U29305MH2019PTC327551 &nbsp;|&nbsp; Ph: +91 9359604384</div>
          <div style={{ color: 'var(--slate-500)' }}>Nashik Office: Flat No. 4A, Sayali Darshan A-Wing, Makhamalabad Road, Nashik-422003.</div>
        </div>
        <div style={{ textAlign: 'right', fontWeight: '600', color: 'var(--slate-600)', whiteSpace: 'nowrap' }}>
          Generated by System
        </div>
      </div>
    </div>
  );

  return (
    <div className="print-template-wrapper" style={{ fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }}>
      <img className="print-only" src="/logo_new.png" alt="Watermark" style={{ position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '420px', opacity: 0.04, zIndex: -1, pointerEvents: 'none' }} />
      
      <div style={{ width: '100%' }}>
        <div className="print-only"><Header /></div>
        <div className="print-body-content" style={{ marginTop: '10px' }}>
          {children}
        </div>
        <div className="print-only" style={{ marginTop: '30px', pageBreakInside: 'avoid', breakInside: 'avoid' }}><Footer /></div>
      </div>
    </div>
  );
};

export default PrintTemplate;
