import jsPDF from 'jspdf';
import 'jspdf-autotable';
import newLogo from '../assets/new_logo.png';

export const exportToPDF = async (title, tableColumn, tableRows, filename, multipleTables = null) => {
  const doc = new jsPDF();
  
  return new Promise((resolve) => {
    const img = new Image();
    img.src = newLogo;
    
    const drawContent = () => {
      const pageWidth = doc.internal.pageSize.getWidth();

      // Add title
      doc.setTextColor(16, 185, 129); // Emerald-500
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text(title.toUpperCase(), 14, 22, { align: "left" });
      
      // Add date
      doc.setTextColor(100, 116, 139); // Slate-500
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30, { align: "left" });
      
      // Add logo (right aligned)
      if (img.width && img.height) {
        const imgWidth = 40; 
        const imgHeight = (img.height * imgWidth) / img.width;
        // Position image so it aligns with the top of the text
        doc.addImage(img, 'PNG', pageWidth - 14 - imgWidth, 12, imgWidth, imgHeight);
      }
      
      // Add line
      doc.setDrawColor(16, 185, 129); // Emerald-500 (Green)
      doc.setLineWidth(0.5);
      doc.line(14, 38, pageWidth - 14, 38);
      
      const totalPagesExp = '{total_pages_count_string}';
      
      const tableStyles = {
        theme: 'grid',
        styles: {
          font: "helvetica",
          fontSize: 9,
          lineColor: [200, 200, 200],
          lineWidth: 0.2
        },
        headStyles: {
          fillColor: [16, 185, 129], // Emerald-500 (Green)
          textColor: 255,
          fontStyle: 'bold'
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252] // Slate-50
        },
        margin: { bottom: 30 },
        didDrawPage: function (data) {
          const pageWidth = doc.internal.pageSize.getWidth();
          const pageHeight = doc.internal.pageSize.getHeight();
          const footerY = pageHeight - 18;

          // Footer Line
          doc.setDrawColor(200, 200, 200);
          doc.setLineWidth(0.5);
          doc.line(14, footerY, pageWidth - 14, footerY);

          // Footer Text
          doc.setTextColor(100, 100, 100);
          
          // Left side text with smaller font
          doc.setFontSize(7);
          doc.setFont("helvetica", "normal");
          doc.text("AARYA INNOVTECH PVT. LTD. CIN: U29305MH2019PTC327551 | +91 9359604384 | https://aaryainnovtech.com/", 14, footerY + 5);
          doc.text("Nashik Office: Flat No.4A, Sayali Darshan A-Wing, Makhamalabad Road, Nashik-422003.", 14, footerY + 9);

          // Right side text
          doc.setFontSize(8);
          const pageStr = "Page " + doc.internal.getNumberOfPages() + " of " + totalPagesExp;
          doc.text(pageStr, pageWidth - 14, footerY + 5, { align: "right" });
          doc.text("Generated by System", pageWidth - 14, footerY + 9, { align: "right" });
        }
      };

      if (multipleTables && multipleTables.length > 0) {
        let currentY = 45;
        multipleTables.forEach((table, index) => {
          if (index > 0) {
            currentY = doc.lastAutoTable.finalY + 15;
            // Check if there is enough space for the title, if not, new page is handled by autoTable mostly, 
            // but for title we might need to check
            if (currentY > doc.internal.pageSize.getHeight() - 40) {
              doc.addPage();
              currentY = 20;
            }
          }
          doc.setFontSize(12);
          doc.setTextColor(220, 38, 38); // Red color for subtitle
          if (table.subtitle.includes("LOW")) {
             doc.setTextColor(234, 179, 8); // Yellow/Orange for low stock
          }
          doc.setFont("helvetica", "bold");
          doc.text(table.subtitle, 14, currentY);
          
          doc.autoTable({ 
            head: [tableColumn], 
            body: table.rows, 
            startY: currentY + 5,
            ...tableStyles
          });
        });
      } else {
        doc.autoTable({ 
          head: [tableColumn], 
          body: tableRows, 
          startY: 45,
          ...tableStyles
        });
      }
      
      // Put total pages
      if (typeof doc.putTotalPages === 'function') {
        doc.putTotalPages(totalPagesExp);
      }

      // Add signature block at the end
      const finalY = doc.lastAutoTable.finalY || 45;
      const pageHeight = doc.internal.pageSize.getHeight();
      
      // Check if there is enough space for signatures (approx 30 units), otherwise add new page
      if (finalY + 30 > pageHeight - 30) {
        doc.addPage();
      }
      
      const sigY = doc.internal.pageSize.getHeight() - 30;
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.5);
      
      // System Administrator Signature
      doc.line(20, sigY, 70, sigY);
      doc.text("System Administrator", 45, sigY + 5, { align: "center" });
      
      // Authorized Signatory Signature
      doc.line(pageWidth - 70, sigY, pageWidth - 20, sigY);
      doc.text("Authorized Signatory", pageWidth - 45, sigY + 5, { align: "center" });

      doc.save(filename);
      resolve();
    };

    img.onload = drawContent;
    img.onerror = drawContent; // If image fails to load, still draw the PDF
  });
};
